### ISSUE TITLE
Missing options for: Architecture / What is the prefix of environment variables used by Symfony?

### ISSUE THREAD

**Issue by mathewpeterson** [ProPheT777/certificationy-web-platform#15]
There are missing options, there should be four but only two are shown.

![screen shot 2015-04-20 at 9 25 16 am](https://cloud.githubusercontent.com/assets/203190/7232132/85fb33ac-e73f-11e4-9647-98c230045098.png)

**Comment by ProPheT777** [comment]
Thank you for reporting it, I will fix it asap

**Comment by ProPheT777** [comment]
Thank you very much because this bug impacted a lot of others answers. :+1:
